name: TDengine Build

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
      - '3.1'
    paths-ignore:
      - 'docs/**'
      - 'packaging/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake \
            libgeos-dev libjansson-dev libsnappy-dev liblzma-dev libz-dev \
            zlib1g pkg-config libssl-dev gawk

      - name: Build and install TDengine
        run: |
          mkdir debug && cd debug
          cmake .. -DBUILD_TOOLS=true \
            -DBUILD_KEEPER=true \
            -DBUILD_HTTP=false \
            -DBUILD_TEST=false \
            -DBUILD_DEPENDENCY_TESTS=false
          make -j 4
          sudo make install
          which taosd
          which taosadapter
          which taoskeeper

      - name: Start taosd
        run: |
          cp /etc/taos/taos.cfg ./
          sudo echo "supportVnodes 256" >> taos.cfg
          nohup sudo taosd -c taos.cfg &

      - name: Start taosadapter
        run: nohup sudo taosadapter &

      - name: Run tests with taosBenchmark
        run: |
          taosBenchmark -t 10 -n 10 -y 
          taos -s "select count(*) from test.meters"
         
      - name: Clean up
        if: always()
        run: |
          if pgrep taosd; then sudo pkill taosd; fi
          if pgrep taosadapter; then sudo pkill taosadapter; fi
